---
title: "Simple document"
output: github_document
---

Import the `FAS_litters.csv` csv using a relative path.

```{r}
library(tidyverse)
library(readxl)
library(haven)
```



```{r}
litters_df <- 
  read_csv("data/FAS_litters.csv")

litters_df = 
  janitor::clean_names(litters_df)


```

import the same data set using an absolute path

```{r, eval=FALSE}
litters_df_abs <- 
  read_csv("~/P8105 Data Science I/data_wrangling_i/data/FAS_litters.csv")
```



```{r}
pups_df <-
  read_csv("data/FAS_pups.csv")

pups_df <-
  janitor::clean_names(pups_df)

#pups_df_abs <- read_csv("~/P8105 Data Science I/data_wrangling_i/data/FAS_pups.csv")
```

## Look at data

```{r}
litters_df

head(litters_df)

tail(litters_df)
```

You can use `view`

```{r, eval=FALSE}
view(litters_df)
```

Look at a data summary

```{r, eval=FALSE}
str(litters_df)
skimr::skim(litters_df)
```

## Options in `read_*`

```{r}
litters_df = 
  read_csv(
    "data/FAS_litters.csv", 
    skip = 10, col_names = FALSE)
```

Look at NA values

```{r}
litters_df <- 
  read_csv("data/FAS_litters.csv",
           na = c("NA", 19))
```

column types

```{r}
litters_df <- 
  read_csv("data/FAS_litters.csv",
           col_types = 
             cols(
               `GD0 weight` = col_character()
             ))
```

## Other file types

Import a xlsx file first.

```{r}
mlb_df <- 
  read_excel("data/mlb11.xlsx")
```

Import a SAS file

```{r}
pulse_df <- 
  read_sas("data/public_pulse_data.sas7bdat")
```


